root = "."
tmp_dir = "tmp

[build]
    cmd = "go run ."
    include_ext = ["go","html", "css", "js"] ## Hot reload 대상
    exclude_dir = ["tmp","build"]            ## 제외
    delay = 1000                             ## Hot reload 대기시간
    